version: '3.8'

services:
  nhentai-bot:
    build: .
    container_name: nhentai-bot
    restart: unless-stopped
    
    environment:
      - TZ=Australia/Sydney
      # 极简穿透语法：不写等号，直接让 Docker 去抓取 Portainer 网页上填的值
      - DISCORD_TOKEN
      - NHENTAI_API_KEY

    volumes:
      - /home/serveradmin/Disks/NC/NC_Files/nextcloud_data/Epub/files/本子/nhentai:/app/local_downloads